algoritmo "Ficha pessoal"
// Função :ex de PA
// Autor :eu memo
// Data : 07/03/2022
// Seção de Declarações 
var
nome:caracter
idade:inteiro
salario:real

inicio
// Seção de Comandos
escreval("Digite seu nome: ")
leia(nome)

escreval("Olá ","prazer em conhece-lo ",nome)

escreval("Digite sua idade: ")
leia(idade)

escreval("Digite seu salario: ")
leia(salario)


 
fimalgoritmo
