algoritmo "TrocarValores"
// Função : A=10,B=20; troque os valores deles.
// Autor :certamente o autor
// Data : 07/03/2022
// Seção de Declarações 
var
a,b,c:inteiro

inicio
// Seção de Comandos00
a <- 10
b <- 20
c <- a
a <- b
b <- c
escreval("*************************")
escreval("* O valor de a é:10",a,"  *")
escreval("*                       *")
escreval("* O valor de b é:20",b,"  *")
escreval("*************************")



fimalgoritmo
