algoritmo "semnome"
// Função :
// Autor :
// Data : 02/05/2022
// Seção de Declarações 
var
a:real
b:real
c:real
d:real
x:real
inicio
// Seção de Comandos
escreval("Digite um número")
leia(a)
escreval("Digite um número")
leia(b)
escreval("Digite um número")
leia(c)
escreval("Digite um número")
leia(d)
a <- a*a
b <- b*b
c <- c*c
d <- d*d
x <- a+b+c+d
escreval("A soma de todos os números dados ao quadrado é: ",x)

fimalgoritmo
